FROM docker.io/library/debian:12.12-slim

RUN apt-get update \
    && apt-get install --yes --no-install-recommends tor=0.4.9.11-0+deb12u1 \
    && rm -rf /var/lib/apt/lists/* \
    && groupmod --gid 10001 debian-tor \
    && usermod --uid 10001 --gid 10001 debian-tor

COPY --chown=root:root torrc /etc/tor/torrc

USER debian-tor
EXPOSE 9050
ENTRYPOINT ["/usr/bin/tor", "-f", "/etc/tor/torrc"]
