import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, writeFile, rm, readFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn, spawnSync } from "node:child_process";
import puppeteer from "puppeteer-core";
import { openAutomaticSession } from "./browser_automatic_session.mjs";

const PROTOTYPE=new URL("..",import.meta.url),FIREFOX=process.env.FIREFOX_PATH??"/usr/bin/firefox";
function ready(server){return new Promise((resolve,reject)=>{let out="";const timer=setTimeout(()=>reject(new Error("démarrage import expiré")),10000);server.stdout.on("data",chunk=>{out+=chunk;const u=out.match(/http:\/\/127\.0\.0\.1:\d+\//);if(u){clearTimeout(timer);resolve({url:u[0]});}});server.once("exit",code=>reject(new Error(`serveur import arrêté (${code})`)));});}
async function waitForDownload(path){let size=-1,stable=0;for(let attempt=0;attempt<120&&stable<3;attempt++){await new Promise(resolve=>setTimeout(resolve,50));try{const current=(await stat(path)).size;stable=current>0&&current===size?stable+1:0;size=current;}catch{stable=0;}}assert.ok(stable>=3,`téléchargement Firefox terminé ${path}`);return size;}

const root=await mkdtemp(join(tmpdir(),"labfy-local-import-browser-")),workspace=join(root,"workspace"),fixtures=join(root,"SPECIMEN_INPUT"),profile=join(root,"firefox"),downloads=join(root,"downloads");
await Promise.all([mkdir(workspace,{mode:0o700}),mkdir(fixtures,{mode:0o700}),mkdir(profile,{mode:0o700}),mkdir(downloads,{mode:0o700})]);
const eml=join(fixtures,"courrier partagé Ω.eml"),eml2=join(fixtures,"courrier lié.eml"),copy=join(fixtures,"copie volontaire.eml"),png=join(fixtures,"image locale.png"),jpg=join(fixtures,"photo locale.jpg");
const shared="From: Source SPECIMEN <source@example.test>\r\nTo: Pivot SPECIMEN <pivot@shared.test>\r\nMessage-ID: <workspace-import@example.test>\r\nSubject: Import navigateur\r\n\r\nCorpus synthétique distinct.\r\n";
await writeFile(eml,shared);await writeFile(copy,shared);
await writeFile(eml2,"From: Autre SPECIMEN <other@example.test>\r\nTo: Pivot SPECIMEN <pivot@shared.test>\r\nMessage-ID: <workspace-linked@example.test>\r\nSubject: Import lié\r\n\r\nMême pivot fictif.\r\n");
await writeFile(png,Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));
await writeFile(jpg,Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAACAAIDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAFB//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AFgrYR//2Q==","base64"));
let server,browser;
try{
 server=spawn("python3",["workspace_server.py","--workspace",workspace,"--bridge","../../tools/local-jobs","--port","0"],{cwd:PROTOTYPE,env:{...process.env,PYTHONUNBUFFERED:"1"},stdio:["ignore","pipe","pipe"]});
 const session=await ready(server);browser=await puppeteer.launch({browser:"firefox",executablePath:FIREFOX,headless:true,userDataDir:profile,args:["--no-remote"],extraPrefsFirefox:{"browser.download.folderList":2,"browser.download.dir":downloads,"browser.download.useDownloadDir":true,"browser.helperApps.neverAsk.saveToDisk":"text/html,application/json,application/pdf,text/plain"}});
 const page=await browser.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.setViewport({width:1440,height:900});await openAutomaticSession(page,session.url);
 await page.waitForSelector("#workspace-create:not([hidden])");await page.type("#workspace-title","Enquête Firefox locale Ω");await page.click("#workspace-create-form button");await page.waitForSelector("#workspace-create[hidden]");
 await page.click("#open-import");const input=await page.$("#import-files");await input.uploadFile(eml,eml2,copy,png,jpg);
 await page.waitForFunction(()=>document.querySelectorAll("#import-list li").length===5&&[...document.querySelectorAll("#import-list li")].every(x=>x.textContent.includes("préparé")),{timeout:20000});
 await page.screenshot({path:"/tmp/labfy-local-import-preparation.png",fullPage:true});await page.click("#import-confirm");
 await page.waitForFunction(()=>document.querySelectorAll(".node").length===5,{timeout:20000});
 await page.click('[data-work-panel="next-panel"]');await page.waitForFunction(()=>document.querySelectorAll("#planner-list input:not(:disabled)").length>=5,{timeout:15000});
 await page.$$eval("#planner-list input:not(:disabled)",xs=>xs.forEach(x=>x.click()));await page.select("#planner-profile","LOCAL_PRUDENT");await page.click("#planner-launch");
 await page.waitForFunction(()=>{const jobs=[...document.querySelectorAll("#jobs-list li")];return jobs.length===5&&jobs.every(job=>job.dataset.jobState==="COMPLETED");},{timeout:45000});
 await page.waitForFunction(()=>document.querySelectorAll(".node").length>3&&document.querySelectorAll(".edge").length>0,{timeout:45000});
 await page.screenshot({path:"/tmp/labfy-local-import-graph.png",fullPage:true});
 await page.evaluate(()=>{const candidate=[...document.querySelectorAll("#object-list button")].find(x=>x.textContent.startsWith("email —"));if(!candidate)throw new Error("preuve e-mail absente");candidate.click();});await page.click('[data-panel="actions-panel"]');await page.evaluate(()=>{const button=[...document.querySelectorAll("#actions button")].find(x=>x.textContent==="Ouvrir la preuve");if(!button)throw new Error("action Ouvrir la preuve absente");button.click();});await page.waitForSelector("#evidence-dialog[open] #observation-list li",{timeout:15000});await page.type("#observation-list li input[placeholder='Motif obligatoire']","Revue navigateur SPECIMEN");await page.evaluate(()=>[...document.querySelectorAll("#observation-list li:first-child button")].find(x=>x.textContent==="Confirmer").click());await page.waitForFunction(()=>document.querySelector("#evidence-status").textContent.includes("journalisée"),{timeout:15000});await page.type("#observation-list li input[placeholder='Motif obligatoire']","Promotion navigateur SPECIMEN");await page.evaluate(()=>[...document.querySelectorAll("#observation-list li:first-child button")].find(x=>x.textContent==="Créer un indicateur").click());await page.waitForFunction(()=>[...document.querySelectorAll("#observation-list li:first-child button")].some(x=>x.textContent==="Retirer l’indicateur"),{timeout:15000});await page.type("#observation-list li input[placeholder='Motif obligatoire']","Retrait navigateur SPECIMEN");await page.evaluate(()=>[...document.querySelectorAll("#observation-list li:first-child button")].find(x=>x.textContent==="Retirer l’indicateur").click());await page.waitForFunction(()=>document.querySelector("#evidence-status").textContent.includes("journalisée"),{timeout:15000});await page.click("#evidence-dialog .dialog-close button");await page.click('[data-report-action="toggle"]');await page.click('[data-work-panel="reports-panel"]');await page.$eval("#report-name",input=>input.value="Rapport navigateur SPECIMEN Ω");await page.click("#report-preview");await page.waitForFunction(()=>document.querySelector("#report-preview-content").textContent.includes("Coupe"),{timeout:15000});await page.click("#report-generate");await page.waitForFunction(()=>document.querySelectorAll("#report-status a").length===5,{timeout:30000});
 const reportHref=await page.$eval('#report-status a[href$="report.json"]',link=>link.getAttribute("href")),reportId=reportHref.split("/")[4],names=["report.json","report.html","report.pdf","manifest.json","NOTICE.txt"],receivedSizes=new Map();
 for(const name of names){await page.$eval(`#report-status a[href$="${name}"]`,link=>link.click());receivedSizes.set(name,await waitForDownload(join(downloads,name)));}
 const manifestBytes=await readFile(join(downloads,"manifest.json")),publishedManifest=await readFile(join(workspace,"exports","reports",reportId,"manifest.json"));assert.deepEqual(manifestBytes,publishedManifest,"manifeste Firefox identique à la publication locale servie");
 const manifest=JSON.parse(manifestBytes);assert.equal(manifest.contract,"labfy.report_manifest.v1");assert.equal(manifest.report_id,reportId);assert.deepEqual(new Set(manifest.files.map(entry=>entry.path)),new Set(names.filter(name=>name!=="manifest.json")));
 for(const entry of manifest.files){const bytes=await readFile(join(downloads,entry.path));assert.equal(bytes.length,entry.size,`taille manifestée ${entry.path}`);assert.equal(receivedSizes.get(entry.path),entry.size,`taille reçue ${entry.path}`);assert.equal(createHash("sha256").update(bytes).digest("hex"),entry.sha256,`SHA-256 ${entry.path}`);}
 assert.equal(receivedSizes.get("manifest.json"),manifestBytes.length,"taille reçue manifest.json");
 const htmlBytes=await readFile(join(downloads,"report.html")),html=htmlBytes.toString("utf8");assert.doesNotMatch(html,/<(?:script|iframe|frame|object|embed|link)\b/i);assert.doesNotMatch(html,/\b(?:src|href|action)\s*=\s*["'](?:https?:|\/\/)/i);assert.doesNotMatch(html,/url\s*\(/i);
 const offlinePage=await browser.newPage();await offlinePage.goto(`file://${join(downloads,"report.html")}`,{waitUntil:"domcontentloaded"});assert.match(await offlinePage.$eval("body",body=>body.textContent),/Rapport navigateur SPECIMEN Ω/);assert.equal(await offlinePage.$$eval("script,iframe,frame,object,embed,link,img,audio,video,source",nodes=>nodes.length),0);await offlinePage.close();
 const pdfText=spawnSync("pdftotext",[join(downloads,"report.pdf"),"-"],{encoding:"utf8"});assert.equal(pdfText.status,0,pdfText.stderr);assert.match(pdfText.stdout.split(/\s+/).join(" "),/Rapport navigateur SPECIMEN Ω/);
 await page.screenshot({path:"/tmp/labfy-local-import-report.png",fullPage:true});await page.setViewport({width:700,height:900});await page.screenshot({path:"/tmp/labfy-local-import-narrow.png",fullPage:true});
 assert.deepEqual(errors,[]);const snapshot=JSON.parse(await readFile(join(workspace,"core-snapshot.json"),"utf8"));assert.equal(snapshot.investigation.synthetic,false);assert.ok(snapshot.nodes.length>5);
 console.log("PASS Firefox import local : cinq analyses terminées et cinq artefacts de rapport téléchargés/vérifiés hors ligne");
}finally{if(browser)await browser.close();if(server){server.kill("SIGINT");await new Promise(r=>server.once("exit",r));}await rm(root,{recursive:true,force:true});}
