#include "dao/financial_dao.h"
#include "core/iban_analyzer.h"
#include "core/bic_validator.h"
#include "database/statement.h"
#include "database/transaction.h"
#include <string.h>
struct BankObservationDao{Database*d;};struct BankReviewDao{Database*d;};
struct BankAccountDao{Database*d;};struct DeclaredBankHolderDao{Database*d;};
struct FinancialTransactionDao{Database*d;};
static GQuark domain(void){return g_quark_from_static_string("financial-dao");}
static void fail(GError**e,const char*m){if(e&&*e==NULL)g_set_error_literal(e,domain(),1,m);}
static gboolean bind(DatabaseStatement*s,int i,const char*v){return v?database_statement_bind_text(s,i,v):database_statement_bind_null(s,i);}
static gboolean done(DatabaseStatement*s){return s&&database_statement_step(s)==DATABASE_STATEMENT_STEP_DONE;}
#define NEW(T,n) T*n(Database*d){if(!d)return NULL;T*r=g_new0(T,1);r->d=d;return r;}
NEW(BankObservationDao,bank_observation_dao_new) NEW(BankReviewDao,bank_review_dao_new)
NEW(BankAccountDao,bank_account_dao_new) NEW(DeclaredBankHolderDao,declared_bank_holder_dao_new)
NEW(FinancialTransactionDao,financial_transaction_dao_new)
void bank_observation_dao_free(BankObservationDao*d){g_free(d);}void bank_review_dao_free(BankReviewDao*d){g_free(d);}
void bank_account_dao_free(BankAccountDao*d){g_free(d);}void declared_bank_holder_dao_free(DeclaredBankHolderDao*d){g_free(d);}
void financial_transaction_dao_free(FinancialTransactionDao*d){g_free(d);}

gboolean bank_observation_dao_insert_analysis(BankObservationDao*d,const BankAnalysisRecord*r,GError**e){BankAnalysisRecord*v=bank_analysis_record_copy(r);if(!d||!v){fail(e,"Analyse bancaire invalide.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_analyses VALUES(?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->investigation_id)&&bind(s,3,v->evidence_id)&&bind(s,4,v->evidence_sha256)&&bind(s,5,v->extraction_method)&&bind(s,6,v->source_kind)&&bind(s,7,v->created_at)&&bind(s,8,bank_origin_to_code(v->origin))&&done(s);database_statement_finalize(s);bank_analysis_record_free(v);if(!ok)fail(e,"Insertion de l’analyse bancaire impossible.");return ok;}
gboolean bank_observation_dao_insert(BankObservationDao*d,const BankObservationRecord*r,GError**e){BankObservationRecord*v=bank_observation_record_copy(r);if(!d||!v){fail(e,"Observation bancaire invalide.");return FALSE;}if(!database_transaction_begin(d->d)){bank_observation_record_free(v);fail(e,"Transaction impossible.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_observations(id,analysis_id,investigation_id,evidence_id,evidence_sha256,occurrence_type,raw_value,start_offset,end_offset,extraction_rule,technical_validation,page_or_image,ocr_run_id,region_x,region_y,region_width,region_height,source_context,origin,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->analysis_id)&&bind(s,3,v->investigation_id)&&bind(s,4,v->evidence_id)&&bind(s,5,v->evidence_sha256)&&bind(s,6,v->occurrence_type)&&bind(s,7,v->raw_value)&&database_statement_bind_int64(s,8,(int64_t)v->start_offset)&&database_statement_bind_int64(s,9,(int64_t)v->end_offset)&&bind(s,10,v->extraction_rule)&&bind(s,11,bank_validation_state_to_code(v->validation))&&bind(s,12,v->page_or_image)&&bind(s,13,v->ocr_run_id)&&bind(s,14,v->region_x)&&bind(s,15,v->region_y)&&bind(s,16,v->region_width)&&bind(s,17,v->region_height)&&bind(s,18,v->source_context)&&bind(s,19,bank_origin_to_code(v->origin))&&bind(s,20,v->created_at)&&done(s);database_statement_finalize(s);for(guint i=0;ok&&i<v->warnings->len;i++){s=database_statement_prepare(d->d,"INSERT INTO bank_observation_warnings VALUES(?,?,?);");ok=s&&bind(s,1,v->id)&&database_statement_bind_int64(s,2,i)&&bind(s,3,g_ptr_array_index(v->warnings,i))&&done(s);database_statement_finalize(s);}ok=ok&&database_transaction_commit(d->d);if(!ok&&database_transaction_is_active(d->d))database_transaction_rollback(d->d);bank_observation_record_free(v);if(!ok)fail(e,"Insertion de l’observation impossible.");return ok;}
static BankValidationState validation_from(const char*v){return g_strcmp0(v,"valid")==0?BANK_VALIDATION_VALID:g_strcmp0(v,"invalid")==0?BANK_VALIDATION_INVALID:g_strcmp0(v,"ambiguous")==0?BANK_VALIDATION_AMBIGUOUS:BANK_VALIDATION_UNVERIFIABLE;}
static BankOrigin origin_from(const char*v){return g_strcmp0(v,"human")==0?BANK_ORIGIN_HUMAN:g_strcmp0(v,"legacy")==0?BANK_ORIGIN_LEGACY:BANK_ORIGIN_AUTOMATIC;}
static BankObservationRecord *read_observation(DatabaseStatement*s){char*v[20]={0};int64_t a=0,b=0;gboolean ok=TRUE;for(int i=0;i<7;i++)ok&=database_statement_column_text(s,i,&v[i]);ok&=database_statement_column_int64(s,7,&a)&&database_statement_column_int64(s,8,&b);for(int i=9;i<20;i++)ok&=database_statement_column_text(s,i,&v[i]);BankObservationRecord x={.id=v[0],.analysis_id=v[1],.investigation_id=v[2],.evidence_id=v[3],.evidence_sha256=v[4],.occurrence_type=v[5],.raw_value=v[6],.start_offset=(gsize)a,.end_offset=(gsize)b,.extraction_rule=v[9],.validation=validation_from(v[10]),.page_or_image=v[11],.ocr_run_id=v[12],.region_x=v[13],.region_y=v[14],.region_width=v[15],.region_height=v[16],.source_context=v[17],.origin=origin_from(v[18]),.created_at=v[19]};BankObservationRecord*r=ok?bank_observation_record_copy(&x):NULL;for(int i=0;i<20;i++)g_free(v[i]);return r;}
static gboolean load_warnings(BankObservationDao*d,BankObservationRecord*r){DatabaseStatement*s=database_statement_prepare(d->d,"SELECT warning FROM bank_observation_warnings WHERE observation_id=? ORDER BY position;");if(!s||!bind(s,1,r->id)){database_statement_finalize(s);return FALSE;}for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW){database_statement_finalize(s);return FALSE;}char*w=NULL;if(!database_statement_column_text(s,0,&w)){database_statement_finalize(s);return FALSE;}g_ptr_array_add(r->warnings,w);}database_statement_finalize(s);return TRUE;}
static GPtrArray *observation_query(BankObservationDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT id,analysis_id,investigation_id,evidence_id,evidence_sha256,occurrence_type,raw_value,start_offset,end_offset,extraction_rule,technical_validation,page_or_image,ocr_run_id,region_x,region_y,region_width,region_height,source_context,origin,created_at FROM bank_observations WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)bank_observation_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW)goto bad;BankObservationRecord*r=read_observation(s);if(!r||!load_warnings(d,r)){bank_observation_record_free(r);goto bad;}g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des observations impossible.");return NULL;}
BankObservationRecord *bank_observation_dao_find(BankObservationDao*d,const char*id,GError**e){GPtrArray*a=observation_query(d,"id=?",id,e);if(!a)return NULL;BankObservationRecord*r=a->len?bank_observation_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
GPtrArray *bank_observation_dao_list_by_evidence(BankObservationDao*d,const char*id,GError**e){return observation_query(d,"evidence_id=?",id,e);}

gboolean bank_review_dao_insert_proposal(BankReviewDao*d,const BankProposalRecord*r,GError**e){BankProposalRecord*v=bank_proposal_record_copy(r);if(!d||!v||v->roles->len!=v->observation_ids->len){bank_proposal_record_free(v);fail(e,"Proposition bancaire invalide.");return FALSE;}if(!database_transaction_begin(d->d)){bank_proposal_record_free(v);return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_proposals VALUES(?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->investigation_id)&&bind(s,3,v->evidence_id)&&database_statement_bind_int64(s,4,v->start_offset)&&database_statement_bind_int64(s,5,v->end_offset)&&database_statement_bind_int64(s,6,v->ambiguous)&&bind(s,7,bank_origin_to_code(v->origin))&&bind(s,8,v->created_at)&&done(s);database_statement_finalize(s);for(guint i=0;ok&&i<v->observation_ids->len;i++){s=database_statement_prepare(d->d,"INSERT INTO bank_proposal_observations VALUES(?,?,?,?);");ok=s&&bind(s,1,v->id)&&bind(s,2,g_ptr_array_index(v->observation_ids,i))&&database_statement_bind_int64(s,3,i)&&bind(s,4,g_ptr_array_index(v->roles,i))&&done(s);database_statement_finalize(s);}for(guint i=0;ok&&i<v->reasons->len;i++){s=database_statement_prepare(d->d,"INSERT INTO bank_proposal_reasons VALUES(?,?,?);");ok=s&&bind(s,1,v->id)&&database_statement_bind_int64(s,2,i)&&bind(s,3,g_ptr_array_index(v->reasons,i))&&done(s);database_statement_finalize(s);}ok=ok&&database_transaction_commit(d->d);if(!ok&&database_transaction_is_active(d->d))database_transaction_rollback(d->d);bank_proposal_record_free(v);if(!ok)fail(e,"Insertion de la proposition impossible.");return ok;}
gboolean bank_review_dao_insert_revision(BankReviewDao*d,const BankRevisionRecord*r,GError**e){BankRevisionRecord*v=bank_revision_record_copy(r);if(!d||!v){fail(e,"Révision bancaire invalide.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_observation_revisions VALUES(?,?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->observation_id)&&bind(s,3,v->corrected_value)&&bind(s,4,v->normalized_value)&&bind(s,5,bank_validation_state_to_code(v->validation))&&bind(s,6,v->factual_notes)&&bind(s,7,v->author)&&bind(s,8,"human")&&bind(s,9,v->created_at)&&done(s);database_statement_finalize(s);bank_revision_record_free(v);if(!ok)fail(e,"Insertion de la révision impossible.");return ok;}
gboolean bank_review_dao_insert_decision(BankReviewDao*d,const BankDecisionRecord*r,GError**e){BankDecisionRecord*v=bank_decision_record_copy(r);if(!d||!v){fail(e,"Décision bancaire invalide.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_decisions VALUES(?,?,?,?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->observation_id)&&bind(s,3,v->proposal_id)&&bind(s,4,v->revision_id)&&bind(s,5,bank_human_decision_to_code(v->decision))&&bind(s,6,"human")&&bind(s,7,v->created_at)&&database_statement_bind_int64(s,8,v->create_account)&&database_statement_bind_int64(s,9,v->reuse_account)&&database_statement_bind_int64(s,10,v->create_holder)&&database_statement_bind_int64(s,11,v->create_transaction)&&done(s);database_statement_finalize(s);bank_decision_record_free(v);if(!ok)fail(e,"Insertion de la décision impossible.");return ok;}
static BankRevisionRecord *read_revision(DatabaseStatement*s){char*v[9]={0};gboolean ok=TRUE;for(int i=0;i<9;i++)ok&=database_statement_column_text(s,i,&v[i]);BankRevisionRecord x={.id=v[0],.observation_id=v[1],.corrected_value=v[2],.normalized_value=v[3],.validation=validation_from(v[4]),.factual_notes=v[5],.author=v[6],.created_at=v[8]};BankRevisionRecord*r=ok?bank_revision_record_copy(&x):NULL;for(int i=0;i<9;i++)g_free(v[i]);return r;}
static GPtrArray *revision_query(BankReviewDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM bank_observation_revisions WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)bank_revision_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW)goto bad;BankRevisionRecord*r=read_revision(s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des révisions impossible.");return NULL;}
GPtrArray *bank_review_dao_list_revisions(BankReviewDao*d,const char*id,GError**e){return revision_query(d,"observation_id=?",id,e);}
BankRevisionRecord *bank_review_dao_find_revision(BankReviewDao*d,const char*id,GError**e){GPtrArray*a=revision_query(d,"id=?",id,e);if(!a)return NULL;BankRevisionRecord*r=a->len?bank_revision_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
static BankHumanDecision decision_from(const char*v){return g_strcmp0(v,"confirmed")==0?BANK_DECISION_CONFIRMED:g_strcmp0(v,"rejected")==0?BANK_DECISION_REJECTED:BANK_DECISION_PROPOSED;}
static BankDecisionRecord *read_decision(DatabaseStatement*s){char*v[7]={0};int64_t flags[4]={0};gboolean ok=TRUE;for(int i=0;i<7;i++)ok&=database_statement_column_text(s,i,&v[i]);for(int i=0;i<4;i++)ok&=database_statement_column_int64(s,7+i,&flags[i]);BankDecisionRecord x={.id=v[0],.observation_id=v[1],.proposal_id=v[2],.revision_id=v[3],.decision=decision_from(v[4]),.created_at=v[6],.create_account=flags[0],.reuse_account=flags[1],.create_holder=flags[2],.create_transaction=flags[3]};BankDecisionRecord*r=ok?bank_decision_record_copy(&x):NULL;for(int i=0;i<7;i++)g_free(v[i]);return r;}
static GPtrArray *decision_query(BankReviewDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM bank_decisions WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)bank_decision_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW)goto bad;BankDecisionRecord*r=read_decision(s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des décisions impossible.");return NULL;}
GPtrArray *bank_review_dao_list_decisions(BankReviewDao*d,const char*id,GError**e){return decision_query(d,"COALESCE(observation_id,proposal_id)=?",id,e);}
BankDecisionRecord *bank_review_dao_find_decision(BankReviewDao*d,const char*id,GError**e){GPtrArray*a=decision_query(d,"id=?",id,e);if(!a)return NULL;BankDecisionRecord*r=a->len?bank_decision_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}

static GPtrArray *proposal_strings(Database*d,const char*sql,const char*id){DatabaseStatement*s=database_statement_prepare(d,sql);GPtrArray*a=g_ptr_array_new_with_free_func(g_free);if(!s||!bind(s,1,id)){database_statement_finalize(s);g_ptr_array_unref(a);return NULL;}for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW){database_statement_finalize(s);g_ptr_array_unref(a);return NULL;}char*v=NULL;if(!database_statement_column_text(s,0,&v)){database_statement_finalize(s);g_ptr_array_unref(a);return NULL;}g_ptr_array_add(a,v);}database_statement_finalize(s);return a;}
static BankProposalRecord *read_proposal(BankReviewDao*d,DatabaseStatement*s){char*v[5]={0};int64_t start=0,end=0,ambiguous=0;gboolean ok=database_statement_column_text(s,0,&v[0])&&database_statement_column_text(s,1,&v[1])&&database_statement_column_text(s,2,&v[2])&&database_statement_column_int64(s,3,&start)&&database_statement_column_int64(s,4,&end)&&database_statement_column_int64(s,5,&ambiguous)&&database_statement_column_text(s,6,&v[3])&&database_statement_column_text(s,7,&v[4]);GPtrArray*ids=ok?proposal_strings(d->d,"SELECT observation_id FROM bank_proposal_observations WHERE proposal_id=? ORDER BY position;",v[0]):NULL;GPtrArray*roles=ids?proposal_strings(d->d,"SELECT role FROM bank_proposal_observations WHERE proposal_id=? ORDER BY position;",v[0]):NULL;GPtrArray*reasons=roles?proposal_strings(d->d,"SELECT reason FROM bank_proposal_reasons WHERE proposal_id=? ORDER BY position;",v[0]):NULL;BankProposalRecord x={.id=v[0],.investigation_id=v[1],.evidence_id=v[2],.start_offset=(gsize)start,.end_offset=(gsize)end,.ambiguous=ambiguous,.origin=origin_from(v[3]),.created_at=v[4],.observation_ids=ids,.roles=roles,.reasons=reasons};BankProposalRecord*r=reasons?bank_proposal_record_copy(&x):NULL;g_clear_pointer(&ids,g_ptr_array_unref);g_clear_pointer(&roles,g_ptr_array_unref);g_clear_pointer(&reasons,g_ptr_array_unref);for(guint i=0;i<5;i++)g_free(v[i]);return r;}
static GPtrArray *proposal_query(BankReviewDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM bank_proposals WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)bank_proposal_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW)goto bad;BankProposalRecord*r=read_proposal(d,s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des propositions impossible.");return NULL;}
BankProposalRecord *bank_review_dao_find_proposal(BankReviewDao*d,const char*id,GError**e){GPtrArray*a=proposal_query(d,"id=?",id,e);if(!a)return NULL;BankProposalRecord*r=a->len?bank_proposal_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
GPtrArray *bank_review_dao_list_proposals_by_evidence(BankReviewDao*d,const char*id,GError**e){return proposal_query(d,"evidence_id=?",id,e);}

static const char *state_code(BankAccountState s){return s==BANK_ACCOUNT_STATE_ACTIVE?"active":s==BANK_ACCOUNT_STATE_CLOSED?"closed":"unknown";}
gboolean bank_account_dao_insert(BankAccountDao*d,const BankAccountRecord*r,GError**e){BankAccountRecord*v=bank_account_record_copy(r);char*canonical=v?iban_analyzer_normalize_canonical(v->iban_normalized):NULL;if(!d||!v||!canonical||!iban_analyzer_validate_canonical(canonical)||g_strcmp0(canonical,v->iban_normalized)!=0||strncmp(v->country_code,canonical,2)!=0||(v->bic&&bic_validator_check(v->bic)!=BIC_VALIDATOR_VALID)){g_free(canonical);bank_account_record_free(v);fail(e,"Compte bancaire confirmé invalide ou non pris en charge.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO bank_accounts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->entity_id)&&bind(s,2,v->investigation_id)&&bind(s,3,canonical)&&bind(s,4,v->country_code)&&bind(s,5,v->bank_code)&&bind(s,6,v->branch_code)&&bind(s,7,v->account_number)&&bind(s,8,v->rib_key)&&bind(s,9,v->bic)&&bind(s,10,v->declared_institution)&&bind(s,11,state_code(v->state))&&bind(s,12,v->first_observed_at)&&bind(s,13,v->last_observed_at)&&bind(s,14,v->factual_notes)&&done(s);database_statement_finalize(s);g_free(canonical);bank_account_record_free(v);if(!ok)fail(e,"Insertion du compte bancaire impossible.");return ok;}
static BankAccountRecord *read_account(DatabaseStatement*s){char*v[14]={0};gboolean ok=TRUE;for(int i=0;i<14;i++)ok&=database_statement_column_text(s,i,&v[i]);BankAccountRecord x={.entity_id=v[0],.investigation_id=v[1],.iban_normalized=v[2],.country_code=v[3],.bank_code=v[4],.branch_code=v[5],.account_number=v[6],.rib_key=v[7],.bic=v[8],.declared_institution=v[9],.state=g_strcmp0(v[10],"active")==0?BANK_ACCOUNT_STATE_ACTIVE:g_strcmp0(v[10],"closed")==0?BANK_ACCOUNT_STATE_CLOSED:BANK_ACCOUNT_STATE_UNKNOWN,.first_observed_at=v[11],.last_observed_at=v[12],.factual_notes=v[13]};BankAccountRecord*r=ok?bank_account_record_copy(&x):NULL;for(int i=0;i<14;i++)g_free(v[i]);return r;}
static GPtrArray *account_query(BankAccountDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM bank_accounts WHERE %s ORDER BY entity_id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)bank_account_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult st=database_statement_step(s);if(st==DATABASE_STATEMENT_STEP_DONE)break;if(st!=DATABASE_STATEMENT_STEP_ROW)goto bad;BankAccountRecord*r=read_account(s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des comptes impossible.");return NULL;}
BankAccountRecord *bank_account_dao_find(BankAccountDao*d,const char*id,GError**e){GPtrArray*a=account_query(d,"entity_id=?",id,e);if(!a)return NULL;BankAccountRecord*r=a->len?bank_account_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
GPtrArray *bank_account_dao_list_by_investigation(BankAccountDao*d,const char*id,GError**e){return account_query(d,"investigation_id=?",id,e);}
gboolean bank_account_dao_add_observation_source(BankAccountDao*d,const char*a,const char*o,const char*decision,const char*kind,const char*at,GError**e){DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,"INSERT INTO bank_account_observation_sources VALUES(?,?,?,?,?);");gboolean ok=s&&bind(s,1,a)&&bind(s,2,o)&&bind(s,3,decision)&&bind(s,4,kind)&&bind(s,5,at)&&done(s);database_statement_finalize(s);if(!ok)fail(e,"Provenance du compte impossible.");return ok;}

static GPtrArray *holder_query(DeclaredBankHolderDao*d,const char*where,const char*id,GError**e);
gboolean declared_bank_holder_dao_insert(DeclaredBankHolderDao*d,const DeclaredBankHolderRecord*r,GError**e){DeclaredBankHolderRecord*v=declared_bank_holder_record_copy(r);if(!d||!v){fail(e,"Titulaire déclaré invalide.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO declared_bank_holders VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?);");gboolean ok=s&&bind(s,1,v->id)&&bind(s,2,v->investigation_id)&&bind(s,3,v->evidence_id)&&bind(s,4,v->observation_id)&&bind(s,5,v->revision_id)&&bind(s,6,v->account_entity_id)&&bind(s,7,v->person_entity_id)&&bind(s,8,v->decision_id)&&bind(s,9,v->declared_name_raw)&&bind(s,10,v->declared_name_corrected)&&bind(s,11,"human")&&bind(s,12,v->created_at)&&bind(s,13,v->factual_notes)&&done(s);database_statement_finalize(s);declared_bank_holder_record_free(v);if(!ok)fail(e,"Insertion du titulaire déclaré impossible.");return ok;}
GPtrArray *declared_bank_holder_dao_list_by_evidence(DeclaredBankHolderDao*d,const char*id,GError**e){return holder_query(d,"evidence_id=?",id,e);}
static DeclaredBankHolderRecord *read_holder(DatabaseStatement*s){char*v[13]={0};gboolean ok=TRUE;for(int i=0;i<13;i++)ok&=database_statement_column_text(s,i,&v[i]);DeclaredBankHolderRecord x={.id=v[0],.investigation_id=v[1],.evidence_id=v[2],.observation_id=v[3],.revision_id=v[4],.account_entity_id=v[5],.person_entity_id=v[6],.decision_id=v[7],.declared_name_raw=v[8],.declared_name_corrected=v[9],.created_at=v[11],.factual_notes=v[12]};DeclaredBankHolderRecord*r=ok?declared_bank_holder_record_copy(&x):NULL;for(int i=0;i<13;i++)g_free(v[i]);return r;}
static GPtrArray *holder_query(DeclaredBankHolderDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM declared_bank_holders WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)declared_bank_holder_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult step=database_statement_step(s);if(step==DATABASE_STATEMENT_STEP_DONE)break;if(step!=DATABASE_STATEMENT_STEP_ROW)goto bad;DeclaredBankHolderRecord*r=read_holder(s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des titulaires déclarés impossible.");return NULL;}
DeclaredBankHolderRecord *declared_bank_holder_dao_find(DeclaredBankHolderDao*d,const char*id,GError**e){GPtrArray*a=holder_query(d,"id=?",id,e);if(!a)return NULL;DeclaredBankHolderRecord*r=a->len?declared_bank_holder_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
GPtrArray *declared_bank_holder_dao_list_by_account(DeclaredBankHolderDao*d,const char*id,GError**e){return holder_query(d,"account_entity_id=?",id,e);}

gboolean financial_transaction_dao_insert(FinancialTransactionDao*d,const FinancialTransactionRecord*r,GError**e){FinancialTransactionRecord*v=financial_transaction_record_copy(r);if(!d||!v){fail(e,"Transaction observée invalide.");return FALSE;}DatabaseStatement*s=database_statement_prepare(d->d,"INSERT INTO financial_transactions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);");const char*vals[]={v->id,v->investigation_id,v->transaction_type,v->observed_date_raw,v->observed_time_raw,v->observed_at_normalized,v->amount_decimal,v->currency,v->observed_status,v->bank_reference,v->reference_type,v->uetr,v->debtor_account_id,v->creditor_account_id,v->declared_payer,v->declared_beneficiary,v->source_institution,v->evidence_id,v->source_observation_id,v->source_proposal_id,v->decision_id,"human",v->factual_notes,v->created_at};gboolean ok=s!=NULL;for(guint i=0;ok&&i<G_N_ELEMENTS(vals);i++)ok=bind(s,i+1,vals[i]);ok=ok&&done(s);database_statement_finalize(s);financial_transaction_record_free(v);if(!ok)fail(e,"Insertion de la transaction observée impossible.");return ok;}
static FinancialTransactionRecord *read_transaction(DatabaseStatement*s){char*v[24]={0};gboolean ok=TRUE;for(int i=0;i<24;i++)ok&=database_statement_column_text(s,i,&v[i]);FinancialTransactionRecord x={.id=v[0],.investigation_id=v[1],.transaction_type=v[2],.observed_date_raw=v[3],.observed_time_raw=v[4],.observed_at_normalized=v[5],.amount_decimal=v[6],.currency=v[7],.observed_status=v[8],.bank_reference=v[9],.reference_type=v[10],.uetr=v[11],.debtor_account_id=v[12],.creditor_account_id=v[13],.declared_payer=v[14],.declared_beneficiary=v[15],.source_institution=v[16],.evidence_id=v[17],.source_observation_id=v[18],.source_proposal_id=v[19],.decision_id=v[20],.factual_notes=v[22],.created_at=v[23]};FinancialTransactionRecord*r=ok?financial_transaction_record_copy(&x):NULL;for(int i=0;i<24;i++)g_free(v[i]);return r;}
static GPtrArray *transaction_query(FinancialTransactionDao*d,const char*where,const char*id,GError**e){char*sql=g_strdup_printf("SELECT * FROM financial_transactions WHERE %s ORDER BY created_at,id;",where);DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,sql);g_free(sql);GPtrArray*a=g_ptr_array_new_with_free_func((GDestroyNotify)financial_transaction_record_free);if(!s||!bind(s,1,id))goto bad;for(;;){DatabaseStatementStepResult st=database_statement_step(s);if(st==DATABASE_STATEMENT_STEP_DONE)break;if(st!=DATABASE_STATEMENT_STEP_ROW)goto bad;FinancialTransactionRecord*r=read_transaction(s);if(!r)goto bad;g_ptr_array_add(a,r);}database_statement_finalize(s);return a;bad:database_statement_finalize(s);g_ptr_array_unref(a);fail(e,"Lecture des transactions impossible.");return NULL;}
FinancialTransactionRecord *financial_transaction_dao_find(FinancialTransactionDao*d,const char*id,GError**e){GPtrArray*a=transaction_query(d,"id=?",id,e);if(!a)return NULL;FinancialTransactionRecord*r=a->len?financial_transaction_record_copy(g_ptr_array_index(a,0)):NULL;g_ptr_array_unref(a);return r;}
GPtrArray *financial_transaction_dao_list_by_evidence(FinancialTransactionDao*d,const char*id,GError**e){return transaction_query(d,"evidence_id=?",id,e);}
GPtrArray *financial_transaction_dao_list_by_account(FinancialTransactionDao*d,const char*id,GError**e){return transaction_query(d,"? IN (debtor_account_id,creditor_account_id)",id,e);}
gboolean financial_transaction_dao_add_observation_source(FinancialTransactionDao*d,const char*t,const char*o,guint p,GError**e){DatabaseStatement*s=database_statement_prepare(d?d->d:NULL,"INSERT INTO financial_transaction_observation_sources VALUES(?,?,?);");gboolean ok=s&&bind(s,1,t)&&bind(s,2,o)&&database_statement_bind_int64(s,3,p)&&done(s);database_statement_finalize(s);if(!ok)fail(e,"Provenance de transaction impossible.");return ok;}
