#include "models/financial_records.h"
#include <string.h>

static char *copy(const char *s){return g_strdup(s);}
static GPtrArray *copy_array(const GPtrArray *a){GPtrArray*r=g_ptr_array_new_with_free_func(g_free);
 if(a){for(guint i=0;i<a->len;i++)g_ptr_array_add(r,g_strdup(g_ptr_array_index((GPtrArray*)a,i)));}return r;}
gboolean financial_record_identifier_valid(const char*v){return v&&v[0]&&strlen(v)<=128;}
gboolean financial_record_utc_valid(const char*v){return v&&strlen(v)==20&&v[4]=='-'&&v[7]=='-'&&v[10]=='T'&&v[13]==':'&&v[16]==':'&&v[19]=='Z';}
gboolean financial_record_sha256_valid(const char*v){if(!v||strlen(v)!=64)return FALSE;for(guint i=0;i<64;i++)if(!g_ascii_isdigit(v[i])&&(v[i]<'a'||v[i]>'f'))return FALSE;return TRUE;}
gboolean financial_record_amount_valid(const char*v){if(!v||!v[0]||strlen(v)>128)return FALSE;gboolean dot=FALSE;guint before=0,after=0;
 for(const char*p=v;*p;p++){if(*p=='.'&&!dot&&before>0){dot=TRUE;continue;}if(!g_ascii_isdigit(*p))return FALSE;if(dot)after++;else before++;}return before>0&&(!dot||after>0);}
#define S(dst,src,field) (dst)->field=copy((src)->field)
BankAnalysisRecord *bank_analysis_record_copy(const BankAnalysisRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->investigation_id)||!financial_record_identifier_valid(s->evidence_id)||!financial_record_sha256_valid(s->evidence_sha256)||!s->extraction_method||!s->source_kind||!financial_record_utc_valid(s->created_at)||s->origin<0||s->origin>=BANK_ORIGIN_COUNT)return NULL;BankAnalysisRecord*r=g_new0(BankAnalysisRecord,1);S(r,s,id);S(r,s,investigation_id);S(r,s,evidence_id);S(r,s,evidence_sha256);S(r,s,extraction_method);S(r,s,source_kind);S(r,s,created_at);r->origin=s->origin;return r;}
BankObservationRecord *bank_observation_record_copy(const BankObservationRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->analysis_id)||!financial_record_identifier_valid(s->investigation_id)||!financial_record_identifier_valid(s->evidence_id)||!financial_record_sha256_valid(s->evidence_sha256)||!s->occurrence_type||!s->raw_value||strlen(s->raw_value)>512||s->end_offset<s->start_offset||s->end_offset-s->start_offset!=strlen(s->raw_value)||!s->extraction_rule||s->validation<0||s->validation>=BANK_VALIDATION_COUNT||s->origin<0||s->origin>=BANK_ORIGIN_COUNT||!financial_record_utc_valid(s->created_at))return NULL;BankObservationRecord*r=g_new0(BankObservationRecord,1);S(r,s,id);S(r,s,analysis_id);S(r,s,investigation_id);S(r,s,evidence_id);S(r,s,evidence_sha256);S(r,s,occurrence_type);S(r,s,raw_value);S(r,s,extraction_rule);S(r,s,page_or_image);S(r,s,ocr_run_id);S(r,s,region_x);S(r,s,region_y);S(r,s,region_width);S(r,s,region_height);S(r,s,source_context);S(r,s,created_at);r->start_offset=s->start_offset;r->end_offset=s->end_offset;r->validation=s->validation;r->origin=s->origin;r->warnings=copy_array(s->warnings);return r;}
BankProposalRecord *bank_proposal_record_copy(const BankProposalRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->investigation_id)||!financial_record_identifier_valid(s->evidence_id)||s->end_offset<s->start_offset||s->origin<0||s->origin>BANK_ORIGIN_HUMAN||!financial_record_utc_valid(s->created_at)||!s->observation_ids||s->observation_ids->len>256)return NULL;BankProposalRecord*r=g_new0(BankProposalRecord,1);S(r,s,id);S(r,s,investigation_id);S(r,s,evidence_id);S(r,s,created_at);r->start_offset=s->start_offset;r->end_offset=s->end_offset;r->ambiguous=s->ambiguous;r->origin=s->origin;r->observation_ids=copy_array(s->observation_ids);r->roles=copy_array(s->roles);r->reasons=copy_array(s->reasons);return r;}
BankRevisionRecord *bank_revision_record_copy(const BankRevisionRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->observation_id)||s->validation<0||s->validation>=BANK_VALIDATION_COUNT||!financial_record_utc_valid(s->created_at))return NULL;BankRevisionRecord*r=g_new0(BankRevisionRecord,1);S(r,s,id);S(r,s,observation_id);S(r,s,corrected_value);S(r,s,normalized_value);S(r,s,factual_notes);S(r,s,author);S(r,s,created_at);r->validation=s->validation;return r;}
BankDecisionRecord *bank_decision_record_copy(const BankDecisionRecord*s){if(!s||!financial_record_identifier_valid(s->id)||((s->observation_id!=NULL)==(s->proposal_id!=NULL))||s->decision<0||s->decision>=BANK_DECISION_COUNT||!financial_record_utc_valid(s->created_at))return NULL;BankDecisionRecord*r=g_new0(BankDecisionRecord,1);S(r,s,id);S(r,s,observation_id);S(r,s,proposal_id);S(r,s,revision_id);S(r,s,created_at);r->decision=s->decision;r->create_account=s->create_account;r->reuse_account=s->reuse_account;r->create_holder=s->create_holder;r->create_transaction=s->create_transaction;return r;}
BankAccountRecord *bank_account_record_copy(const BankAccountRecord*s){if(!s||!financial_record_identifier_valid(s->entity_id)||!financial_record_identifier_valid(s->investigation_id)||!s->iban_normalized||!s->country_code||s->state<0||s->state>BANK_ACCOUNT_STATE_CLOSED||!financial_record_utc_valid(s->first_observed_at)||!financial_record_utc_valid(s->last_observed_at))return NULL;BankAccountRecord*r=g_new0(BankAccountRecord,1);S(r,s,entity_id);S(r,s,investigation_id);S(r,s,iban_normalized);S(r,s,country_code);S(r,s,bank_code);S(r,s,branch_code);S(r,s,account_number);S(r,s,rib_key);S(r,s,bic);S(r,s,declared_institution);S(r,s,first_observed_at);S(r,s,last_observed_at);S(r,s,factual_notes);r->state=s->state;return r;}
DeclaredBankHolderRecord *declared_bank_holder_record_copy(const DeclaredBankHolderRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->investigation_id)||!financial_record_identifier_valid(s->evidence_id)||!s->declared_name_raw||strlen(s->declared_name_raw)>512||!financial_record_utc_valid(s->created_at))return NULL;DeclaredBankHolderRecord*r=g_new0(DeclaredBankHolderRecord,1);S(r,s,id);S(r,s,investigation_id);S(r,s,evidence_id);S(r,s,observation_id);S(r,s,revision_id);S(r,s,account_entity_id);S(r,s,person_entity_id);S(r,s,decision_id);S(r,s,declared_name_raw);S(r,s,declared_name_corrected);S(r,s,created_at);S(r,s,factual_notes);return r;}
FinancialTransactionRecord *financial_transaction_record_copy(const FinancialTransactionRecord*s){if(!s||!financial_record_identifier_valid(s->id)||!financial_record_identifier_valid(s->investigation_id)||!financial_record_identifier_valid(s->evidence_id)||!financial_record_identifier_valid(s->decision_id)||!s->transaction_type||!financial_record_amount_valid(s->amount_decimal)||!financial_record_utc_valid(s->created_at)||(s->currency&&(strlen(s->currency)!=3||!g_ascii_isupper(s->currency[0])||!g_ascii_isupper(s->currency[1])||!g_ascii_isupper(s->currency[2])))||(s->uetr&&!g_uuid_string_is_valid(s->uetr)))return NULL;FinancialTransactionRecord*r=g_new0(FinancialTransactionRecord,1);S(r,s,id);S(r,s,investigation_id);S(r,s,transaction_type);S(r,s,observed_date_raw);S(r,s,observed_time_raw);S(r,s,observed_at_normalized);S(r,s,amount_decimal);S(r,s,currency);S(r,s,observed_status);S(r,s,bank_reference);S(r,s,reference_type);S(r,s,uetr);S(r,s,debtor_account_id);S(r,s,creditor_account_id);S(r,s,declared_payer);S(r,s,declared_beneficiary);S(r,s,source_institution);S(r,s,evidence_id);S(r,s,source_observation_id);S(r,s,source_proposal_id);S(r,s,decision_id);S(r,s,factual_notes);S(r,s,created_at);return r;}
#define F(x) g_free(x)
void bank_analysis_record_free(BankAnalysisRecord*r){if(!r)return;F(r->id);F(r->investigation_id);F(r->evidence_id);F(r->evidence_sha256);F(r->extraction_method);F(r->source_kind);F(r->created_at);F(r);}
void bank_observation_record_free(BankObservationRecord*r){if(!r)return;F(r->id);F(r->analysis_id);F(r->investigation_id);F(r->evidence_id);F(r->evidence_sha256);F(r->occurrence_type);F(r->raw_value);F(r->extraction_rule);F(r->page_or_image);F(r->ocr_run_id);F(r->region_x);F(r->region_y);F(r->region_width);F(r->region_height);F(r->source_context);F(r->created_at);g_clear_pointer(&r->warnings,g_ptr_array_unref);F(r);}
void bank_proposal_record_free(BankProposalRecord*r){if(!r)return;F(r->id);F(r->investigation_id);F(r->evidence_id);F(r->created_at);g_clear_pointer(&r->observation_ids,g_ptr_array_unref);g_clear_pointer(&r->roles,g_ptr_array_unref);g_clear_pointer(&r->reasons,g_ptr_array_unref);F(r);}
void bank_revision_record_free(BankRevisionRecord*r){if(!r)return;F(r->id);F(r->observation_id);F(r->corrected_value);F(r->normalized_value);F(r->factual_notes);F(r->author);F(r->created_at);F(r);}
void bank_decision_record_free(BankDecisionRecord*r){if(!r)return;F(r->id);F(r->observation_id);F(r->proposal_id);F(r->revision_id);F(r->created_at);F(r);}
void bank_account_record_free(BankAccountRecord*r){if(!r)return;F(r->entity_id);F(r->investigation_id);F(r->iban_normalized);F(r->country_code);F(r->bank_code);F(r->branch_code);F(r->account_number);F(r->rib_key);F(r->bic);F(r->declared_institution);F(r->first_observed_at);F(r->last_observed_at);F(r->factual_notes);F(r);}
void declared_bank_holder_record_free(DeclaredBankHolderRecord*r){if(!r)return;F(r->id);F(r->investigation_id);F(r->evidence_id);F(r->observation_id);F(r->revision_id);F(r->account_entity_id);F(r->person_entity_id);F(r->decision_id);F(r->declared_name_raw);F(r->declared_name_corrected);F(r->created_at);F(r->factual_notes);F(r);}
void financial_transaction_record_free(FinancialTransactionRecord*r){if(!r)return;F(r->id);F(r->investigation_id);F(r->transaction_type);F(r->observed_date_raw);F(r->observed_time_raw);F(r->observed_at_normalized);F(r->amount_decimal);F(r->currency);F(r->observed_status);F(r->bank_reference);F(r->reference_type);F(r->uetr);F(r->debtor_account_id);F(r->creditor_account_id);F(r->declared_payer);F(r->declared_beneficiary);F(r->source_institution);F(r->evidence_id);F(r->source_observation_id);F(r->source_proposal_id);F(r->decision_id);F(r->factual_notes);F(r->created_at);F(r);}
